# Generated by Django 5.2.16 on 2026-07-10 18:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='capacity',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='slot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
