# Generated by Django 5.2.16 on 2026-07-12 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_slot_capacity_slot_created_at_slot_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lunch_start', models.TimeField(blank=True, null=True)),
                ('lunch_end', models.TimeField(blank=True, null=True)),
                ('slot_duration', models.PositiveIntegerField(default=30, help_text='Minutes')),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('is_closed', models.BooleanField(default=False)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.office')),
            ],
            options={
                'ordering': ['office', 'day_of_week'],
                'unique_together': {('office', 'day_of_week')},
            },
        ),
    ]
